/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.glassfish.javax.faces)
    api(libs.org.hibernate.hibernate.core)
    api(libs.org.apache.derby.derby)
    api(libs.org.apache.derby.derbyclient)
    api(libs.javax.xml.bind.jaxb.api)
    api(libs.org.primefaces.primefaces)
    api(libs.org.postgresql.postgresql)
}

group = "IPWA02"
version = "1.0-SNAPSHOT"
description = "LZTH"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
